[project]
name = "hybrid-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Saad Ali Asghar", email = "saadaliasghar1045@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.142.4",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "python-dotenv>=1.2.4",
    "scikit-learn>=1.9.1",
    "scikit-surprise>=1.1.5",
    "uvicorn>=0.54.0",
]

[project.scripts]
hybrid-model = "hybrid_model:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
